# Generated by Django 5.0 on 2024-02-18 06:45

import Product.image_urls
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='name of category')),
                ('description', models.TextField(blank=True, max_length=80, null=True, verbose_name='description of category')),
                ('image', models.ImageField(blank=True, null=True, upload_to=Product.image_urls.get_main_category, verbose_name='image of category')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': ' main category',
                'verbose_name_plural': 'main categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True, verbose_name='product name')),
                ('description', models.TextField(blank=True, max_length=100, null=True, verbose_name='product description')),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True, verbose_name='product price')),
                ('cost', models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True, verbose_name='product cost')),
                ('image', models.ImageField(blank=True, null=True, upload_to=Product.image_urls.get_product, verbose_name=' product image ')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('title', models.CharField(blank=True, max_length=20, null=True, verbose_name='product name')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.brand')),
                ('customize', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.customizevariant')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.variant')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': "product's",
            },
        ),
        migrations.CreateModel(
            name='Product_Accessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessories_product', models.ManyToManyField(related_name='accessories_products', to='Product.product', verbose_name='Accessories')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mainAccessory_product', to='Product.product')),
            ],
            options={
                'verbose_name': 'Product_Accessory',
                'verbose_name_plural': 'Product_Accessories',
            },
        ),
        migrations.CreateModel(
            name='Product_Alternative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alternative_product', models.ManyToManyField(related_name='alternative_products', to='Product.product', verbose_name='Alternative')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_product', to='Product.product')),
            ],
            options={
                'verbose_name': 'Product_Alternative',
                'verbose_name_plural': 'Product_Alternatives',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='name of category')),
                ('description', models.TextField(blank=True, max_length=80, null=True, verbose_name='description of category')),
                ('image', models.ImageField(blank=True, null=True, upload_to=Product.image_urls.get_sub_category, verbose_name='image of category')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('main_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Product.maincategorymodel', verbose_name='main category')),
            ],
            options={
                'verbose_name': 'sub category',
                'verbose_name_plural': ' sub categories',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Product.subcategory'),
        ),
    ]
