# Generated by Django 5.0 on 2024-02-18 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
        ('settings', '0004_alter_variant_color_alter_variant_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='variant',
        ),
        migrations.AddField(
            model_name='product',
            name='variant',
            field=models.ManyToManyField(blank=True, null=True, to='settings.variant'),
        ),
    ]
