# Generated by Django 5.0 on 2024-02-18 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_remove_product_variant_product_variant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
