# Generated by Django 5.0 on 2024-01-02 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_alter_product_cost_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat_parent',
            field=models.ForeignKey(blank=True, limit_choices_to={'cat_parent': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='Product.category'),
        ),
    ]
