# Generated by Django 5.0 on 2024-01-02 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0006_alter_category_cat_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'product', 'verbose_name_plural': 'product'},
        ),
        migrations.CreateModel(
            name='Product_Alternative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alternative_product', models.ManyToManyField(related_name='alternative_products', to='Product.product')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_product', to='Product.product')),
            ],
            options={
                'verbose_name': 'Product_Alternative',
                'verbose_name_plural': 'Product_Alternatives',
            },
        ),
    ]
