# Generated by Django 5.0 on 2024-01-03 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0007_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Accessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessories_product', models.ManyToManyField(related_name='accessories_products', to='Product.product')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mainAccessory_product', to='Product.product')),
            ],
            options={
                'verbose_name': 'ProductAccessory_Alternative',
                'verbose_name_plural': 'ProductAccessories_Alternatives',
            },
        ),
    ]
