# Generated by Django 5.0 on 2024-01-03 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0008_product_accessories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product_accessories',
            options={'verbose_name': 'Product_Accessory', 'verbose_name_plural': 'Product_Accessories'},
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, max_length=80, null=True, verbose_name='description of category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category/', verbose_name='image of category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='name of category'),
        ),
        migrations.AlterField(
            model_name='product_accessories',
            name='accessories_product',
            field=models.ManyToManyField(related_name='accessories_products', to='Product.product', verbose_name='Accessories'),
        ),
        migrations.AlterField(
            model_name='product_alternative',
            name='alternative_product',
            field=models.ManyToManyField(related_name='alternative_products', to='Product.product', verbose_name='Alternative'),
        ),
    ]
