# Generated by Django 5.0 on 2024-01-17 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0010_product_brand_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=False),
        ),
    ]
