# Generated by Django 5.0 on 2024-01-23 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0017_remove_product_productimage_product_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True, verbose_name='name')),
                ('description', models.TextField(blank=True, max_length=80, null=True, verbose_name='description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='category/main', verbose_name='image main category')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'main category',
                'verbose_name_plural': 'main categories',
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Product.maincategory'),
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True, verbose_name='name sub cat')),
                ('description', models.TextField(blank=True, max_length=80, null=True, verbose_name='description sub cat')),
                ('image', models.ImageField(blank=True, null=True, upload_to='category/sub', verbose_name='image sub cat')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('main_category', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Product.maincategory', verbose_name='sub category')),
            ],
            options={
                'verbose_name': 'sub category',
                'verbose_name_plural': 'sub categories',
            },
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
