# Generated by Django 5.0 on 2024-01-24 09:30

import Product.image_urls
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0019_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=Product.image_urls.get_product, verbose_name='image product'),
        ),
    ]
