# Generated by Django 5.0 on 2024-01-24 09:40

import Product.image_urls
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0020_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maincategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=Product.image_urls.get_main_category, verbose_name='image main category'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=Product.image_urls.get_sub_category, verbose_name='image sub cat'),
        ),
    ]
