# Generated by Django 5.0 on 2024-01-30 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0021_alter_maincategory_image_alter_subcategory_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MainCategory',
            new_name='MainCategoryModel',
        ),
    ]
