# Generated by Django 5.0 on 2024-02-07 07:36

import Product.image_urls
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0024_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.AlterModelOptions(
            name='maincategorymodel',
            options={'verbose_name': ' main category', 'verbose_name_plural': 'main categories'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'sub category', 'verbose_name_plural': ' sub categories'},
        ),
        migrations.AlterField(
            model_name='maincategorymodel',
            name='description',
            field=models.TextField(blank=True, max_length=80, null=True, verbose_name='description of category'),
        ),
        migrations.AlterField(
            model_name='maincategorymodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=Product.image_urls.get_main_category, verbose_name='image of category'),
        ),
        migrations.AlterField(
            model_name='maincategorymodel',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='name of category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=Product.image_urls.get_product, verbose_name=' product image '),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='description',
            field=models.TextField(blank=True, max_length=80, null=True, verbose_name='description of category'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=Product.image_urls.get_sub_category, verbose_name='image of category'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='name of category'),
        ),
    ]
