# Generated by Django 5.0 on 2024-02-07 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0025_delete_cart_alter_maincategorymodel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'product', 'verbose_name_plural': "product's"},
        ),
    ]
