# Generated by Django 5.0 on 2024-02-18 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customizevariant',
            name='main',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.var_main', verbose_name='sub_variation'),
        ),
        migrations.AlterField(
            model_name='customizevariant',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='name_sub'),
        ),
    ]
