# Generated by Django 5.0 on 2024-02-18 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_alter_variant_color_alter_variant_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=7, null=True, verbose_name='price'),
        ),
        migrations.AddField(
            model_name='variant',
            name='quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='quantity'),
        ),
    ]
