# Generated by Django 5.0 on 2024-02-18 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_variant_price_variant_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=7, null=True, verbose_name='price of variant'),
        ),
    ]
