# Generated by Django 5.0 on 2024-03-03 07:32

import settings.var_image
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_alter_variant_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=settings.var_image.get_image, verbose_name='image variant')),
            ],
            options={
                'verbose_name': 'image variant',
                'verbose_name_plural': 'image variants',
            },
        ),
    ]
